package br.com.felipe.termometro.lancamentoplanejado.infra;
import br.com.felipe.termometro.lancamentoplanejado.domain.*;
import br.com.felipe.termometro.shared.Dinheiro;
import jakarta.persistence.*;
import java.math.BigDecimal;import java.time.*;import java.util.*;
import lombok.*;
@Entity @Table(name="lancamento_planejado") @Getter @NoArgsConstructor(access=AccessLevel.PROTECTED)
class LancamentoPlanejadoJpaEntity{
 @Id private UUID id; @Column(nullable=false) private String descricao; @Enumerated(EnumType.STRING) @Column(nullable=false) private TipoLancamentoPlanejado tipo; @Column(nullable=false,precision=14,scale=2) private BigDecimal valor; @Column(nullable=false) private LocalDate vencimento; @Enumerated(EnumType.STRING) @Column(nullable=false) private StatusLancamentoPlanejado status; @Column(name="conta_origem_id") private UUID contaOrigemId; @Column(name="conta_destino_id") private UUID contaDestinoId; private String categoria; private String grupo; private String natureza; @Column(name="cartao_manual_id") private UUID cartaoManualId; @Column(name="transacao_id") private UUID transacaoId; @Enumerated(EnumType.STRING) @Column(name="marcacao_planejamento",nullable=false) private MarcacaoPlanejamento marcacaoPlanejamento; @Enumerated(EnumType.STRING) @Column(name="origem_receita") private OrigemReceita origemReceita; @Column(name="serie_id") private UUID serieId; @Column(name="dia_recorrencia") private Integer diaRecorrencia; @Column(name="atualizado_em",nullable=false) private OffsetDateTime atualizadoEm;
 LancamentoPlanejadoJpaEntity(LancamentoPlanejado x){id=x.id();descricao=x.descricao();tipo=x.tipo();valor=x.valor().valor();vencimento=x.vencimento();status=x.status();contaOrigemId=x.contaOrigemId();contaDestinoId=x.contaDestinoId();categoria=x.categoria()==null?null:x.categoria().nome();grupo=x.categoria()==null?null:x.categoria().grupo();natureza=x.categoria()==null?null:x.categoria().natureza();cartaoManualId=x.cartaoManualId();transacaoId=x.transacaoId();marcacaoPlanejamento=x.marcacaoPlanejamento();origemReceita=x.origemReceita();serieId=x.serieId();diaRecorrencia=x.diaRecorrencia();atualizadoEm=OffsetDateTime.now();}
 LancamentoPlanejado paraDominio(){CategoriaDoLancamento c=categoria==null?null:new CategoriaDoLancamento(categoria,grupo,natureza);return new LancamentoPlanejado(id,descricao,tipo,Dinheiro.de(valor),vencimento,status,contaOrigemId,contaDestinoId,c,cartaoManualId,transacaoId,marcacaoPlanejamento,origemReceita,serieId,diaRecorrencia);}
}
