package br.com.felipe.termometro.lancamentoplanejado.application.service;
import br.com.felipe.termometro.classificacao.application.repository.RegraDeCategorizacaoRepository;import br.com.felipe.termometro.classificacao.domain.Categoria;import br.com.felipe.termometro.classificacao.domain.GrupoDeCategoria;import br.com.felipe.termometro.classificacao.domain.Natureza;import br.com.felipe.termometro.lancamentoplanejado.application.repository.LancamentoPlanejadoRepository;import br.com.felipe.termometro.lancamentoplanejado.domain.*;import br.com.felipe.termometro.ingestao.application.repository.TransacaoRepository;import br.com.felipe.termometro.ingestao.application.service.ImportacaoProcessadaService;import br.com.felipe.termometro.ingestao.domain.*;import br.com.felipe.termometro.contamanual.application.repository.ContaManualRepository;import br.com.felipe.termometro.contamanual.domain.ContaManual;import br.com.felipe.termometro.shared.Dinheiro;import java.util.*;import lombok.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class LancamentoPlanejadoApplicationService{
 private final LancamentoPlanejadoRepository repository;
 private final TransacaoRepository transacaoRepository;
 private final ImportacaoProcessadaService importacaoProcessadaService;
 private final ContaManualRepository contaManualRepository;
 private final RegraDeCategorizacaoRepository regraDeCategorizacaoRepository;
 public List<LancamentoPlanejado> listaPendentes(){return repository.buscaPendentes();}
 public LancamentoPlanejado salva(LancamentoPlanejado item){return repository.buscaPorId(item.id()).map(existente->edita(item)).orElseGet(()->repository.salva(item));}
 public LancamentoPlanejado edita(LancamentoPlanejado item){LancamentoPlanejado existente=repository.buscaPorId(item.id()).orElseThrow(()->new IllegalArgumentException("lançamento não encontrado"));if(existente.status()!=StatusLancamentoPlanejado.PENDENTE)throw new IllegalStateException("só lançamento pendente pode ser editado");LancamentoPlanejado editado=new LancamentoPlanejado(item.id(),item.descricao(),item.tipo(),item.valor(),item.vencimento(),existente.status(),item.contaOrigemId(),item.contaDestinoId(),item.categoria(),item.cartaoManualId(),existente.transacaoId(),item.marcacaoPlanejamento(),item.origemReceita());return repository.salva(editado);}
 @Transactional public LancamentoPlanejado liquidar(UUID id){LancamentoPlanejado item=repository.buscaPorId(id).orElseThrow(()->new IllegalArgumentException("lançamento não encontrado"));if(item.status()==StatusLancamentoPlanejado.LIQUIDADO)return item;LancamentoPlanejado liquidado=item.liquidar();if(item.tipo()==TipoLancamentoPlanejado.TRANSFERENCIA){String referencia="Transferência: "+item.descricao();transacaoRepository.salvaTodasDoLancamentoPlanejado(item.id(),"manual-conta-"+item.contaOrigemId(),List.of(movimento(item,referencia,item.valor().negado())));transacaoRepository.salvaTodasDoLancamentoPlanejado(item.id(),"manual-conta-"+item.contaDestinoId(),List.of(movimento(item,referencia,item.valor())));debitaConta(item.contaOrigemId(),item.valor());creditaConta(item.contaDestinoId(),item.valor());importacaoProcessadaService.processa(List.of());}else{aprendeCategoria(item);Dinheiro valor=item.tipo()==TipoLancamentoPlanejado.RECEITA?item.valor():item.valor().negado();List<TransacaoBruta> novas=transacaoRepository.salvaTodasDoLancamentoPlanejado(item.id(),"manual-planejado",List.of(movimento(item,item.descricao(),valor)));if(item.tipo()==TipoLancamentoPlanejado.DESPESA&&item.contaOrigemId()!=null)debitaConta(item.contaOrigemId(),item.valor());if(item.tipo()==TipoLancamentoPlanejado.RECEITA&&item.contaDestinoId()!=null)creditaConta(item.contaDestinoId(),item.valor());importacaoProcessadaService.processa(novas);}return repository.salva(liquidado);}
 @Transactional public LancamentoPlanejado reabrir(UUID id){LancamentoPlanejado item=repository.buscaPorId(id).orElseThrow(()->new IllegalArgumentException("lançamento não encontrado"));if(item.status()==StatusLancamentoPlanejado.PENDENTE)return item;LancamentoPlanejado reaberto=item.reabrir();transacaoRepository.ignoraMovimentosDoLancamentoPlanejado(item.id());if(item.tipo()==TipoLancamentoPlanejado.TRANSFERENCIA){creditaConta(item.contaOrigemId(),item.valor());debitaConta(item.contaDestinoId(),item.valor());}else{if(item.tipo()==TipoLancamentoPlanejado.DESPESA&&item.contaOrigemId()!=null)creditaConta(item.contaOrigemId(),item.valor());if(item.tipo()==TipoLancamentoPlanejado.RECEITA&&item.contaDestinoId()!=null)debitaConta(item.contaDestinoId(),item.valor());}return repository.salva(reaberto);}
 @Transactional public LancamentoPlanejado cancelar(UUID id){LancamentoPlanejado item=repository.buscaPorId(id).orElseThrow(()->new IllegalArgumentException("lançamento não encontrado"));return repository.salva(item.cancelar());}
 @Transactional public void remove(UUID id){LancamentoPlanejado item=repository.buscaPorId(id).orElseThrow(()->new IllegalArgumentException("lançamento não encontrado"));if(item.status()==StatusLancamentoPlanejado.LIQUIDADO)throw new IllegalStateException("reabra o lançamento antes de excluir");repository.remove(id);}
 private void aprendeCategoria(LancamentoPlanejado item){if(item.tipo()!=TipoLancamentoPlanejado.DESPESA||item.categoria()==null)return;Categoria categoria=new Categoria(item.categoria().nome(),GrupoDeCategoria.valueOf(item.categoria().grupo()),Natureza.valueOf(item.categoria().natureza()));regraDeCategorizacaoRepository.aprende(Normalizador.chaveDeEstabelecimento(item.descricao()),categoria);}
 private void debitaConta(UUID id,Dinheiro valor){ContaManual conta=conta(id);contaManualRepository.salva(conta.debitar(valor));}
 private void creditaConta(UUID id,Dinheiro valor){ContaManual conta=conta(id);contaManualRepository.salva(conta.creditar(valor));}
 private ContaManual conta(UUID id){return contaManualRepository.buscaPorId(id).orElseThrow(()->new IllegalArgumentException("conta manual não encontrada"));}
 private static TransacaoBruta movimento(LancamentoPlanejado item,String descricao,Dinheiro valor){return new TransacaoBruta(item.vencimento(),null,descricao,descricao,valor,null,null,SecaoFatura.MOVIMENTO_CONTA,null,Origem.MANUAL,0);}
}
