export const CATEGORIAS_LANCAMENTO = [
  { nome: "Alimentação", grupo: "ALIMENTACAO" },
  { nome: "Assinaturas e serviços", grupo: "ASSINATURAS" },
  { nome: "Bares e restaurantes", grupo: "ALIMENTACAO" },
  { nome: "Casa", grupo: "MORADIA" },
  { nome: "Compras", grupo: "COMPRAS" },
  { nome: "Cuidados pessoais", grupo: "SAUDE" },
  { nome: "Dívidas e empréstimos", grupo: "DIVIDA" },
  { nome: "Educação", grupo: "SERVICOS" },
  { nome: "Família e filhos", grupo: "OUTROS" },
  { nome: "Impostos e Taxas", grupo: "IMPOSTOS" },
  { nome: "Investimentos", grupo: "OUTROS" },
  { nome: "Lazer e hobbies", grupo: "LAZER" },
  { nome: "Mercado", grupo: "ALIMENTACAO" },
  { nome: "Pets", grupo: "OUTROS" },
  { nome: "Presentes e doações", grupo: "OUTROS" },
  { nome: "Roupas", grupo: "VESTUARIO" },
  { nome: "Saúde", grupo: "SAUDE" },
  { nome: "Trabalho", grupo: "SERVICOS" },
  { nome: "Transporte", grupo: "TRANSPORTE" },
  { nome: "Viagem", grupo: "LAZER" },
  { nome: "Outros", grupo: "OUTROS" },
] as const;
